### ISSUE TITLE
各種SNSアカウントの確保

### ISSUE THREAD

**Issue by mnmonzk** [mc-oops/Conference#1]

**Comment by SilversCat** [comment]
- Twitter
- Google+
- Youtube
- ニコニコ動画

この4種類があれば十分だと思います。広報力がなければプロジェクトは衰退するでしょう。

**Comment by mnmonzk** [comment]
@SilversCat Google+は非常に限られたスペースであり、広報には適していないと考えます。
それ以外でしたら、非常に良いと思います。

**Comment by SilversCat** [comment]
@mnmonzk それもそうですが、どうせYoutubeチャンネルを作成するとおまけみたいについてくるので、Twitterと連動させ、適当に運用すれば良いのではないでしょうか？

**Comment by mnmonzk** [comment]
では、継続的にTwitterを利用し、月に２回ほど進捗情報的な何かをYT + ニコニコで宣伝する感じで問題ないでしょうか。
@mc-oops/team

**Comment by tearaikazuki** [comment]
@mnmonzk 問題無いと思います

**Comment by TeckService** [comment]
@mnmonzk いいのでは。

**Comment by SilversCat** [comment]
@mnmonzk 問題ないかと

**Comment by junT58** [comment]
私も問題ないと思います。

**Comment by PNGRU** [comment]
@mnmonzk 問題無いと思います。
