### ISSUE TITLE
チーフの決定

### ISSUE THREAD

**Issue by SilversCat** [mc-oops/Conference#2]

**Comment by SilversCat** [comment]
ところで、このチーフとやらは一体どのようなことを行うのでしょうか？

**Comment by mnmonzk** [comment]
チーフについて軽く説明させていただきます。

チーフとは、WEB(フロントエンド) / サーバ(バックエンド)の開発リーダのようなものです。
チーフは、各開発チームの進捗情報をプロジェクトマネージャ(後ほど決定)に連絡しつつ、チームの統合を行います。

**Comment by SilversCat** [comment]
@mnmonzk なるほど、有難うございます。

**Comment by mnmonzk** [comment]
こちらについては、後々決めるべき時(開発割当)が来ると思いますので、保留でいいと思います。

**Comment by SilversCat** [comment]
そうですね。別のことをすすめましょう。

**Comment by mnmonzk** [comment]
@mc-oops/developer チームが確定しましたので、こちらを進めさせていただきます。
現在、2-2-1(BE - FE - PL)の人数配分となっており、PL担当は１人しかいないため、自動的に @kory33 氏がPLのチーフとなります。

ここで決めることは、残りのBE、FEチームの中でどちらか１人をチーフとして上げていただきます。
こちらで議論しても構いませんし、Discord内で決めていただきこちらに報告していただいても構いません。

期日は本日の２２時００分までにします。
よろしくお願いします。

**Comment by SilversCat** [comment]
じゃあバックエンドのチーフは私で。

**Comment by SilversCat** [comment]
これ以上意見が出ないので、これで決定でよろしいでしょうか？

**Comment by mnmonzk** [comment]
では、
PL @kory33 / FE @PNGRU  / BE @SilversCat 
で確定します。
