### ISSUE TITLE
使用言語及び、ライブラリの決定

### ISSUE THREAD

**Issue by mnmonzk** [mc-oops/Conference#3]

**Comment by SilversCat** [comment]
私はSpigot Plugin部分にKotlin、Web部分はPythonで開発することを提案しますが、どうでしょうか？

**Comment by TeckService** [comment]
@SilversCat 
すみません。Pythonという言語を理解していないので言いにくいのですが、
軽量化や開発の容易さの面からみて、ウェブ部分はPHPのほうが良いのでは？
Pythonだと、見た限り現段階のスタッフでは扱える方が少なそう...に見えただけです。

**Comment by mnmonzk** [comment]
@SilversCat こちらもKotlinを扱える方が少ないと感じるのですが、Javaではダメでしょうか。

**Comment by SilversCat** [comment]
@TeckService うーむ、PHPはどうもロジックとビュー部分を分けることが難しいのとセキュリティホールの多いというネガティブなイメージがありますが、どうでしょうか？APS.NETはWindowsサーバーを用意できないと動作しません。（.NET Coreは例外）

@mnmonzk Javaでも良いかと思います。ただ、Kotlinにすると幾つか便利な関数が追加されます。そのライブラリもApacheライセンスで扱いやすいですし、文法もJavaに似ているので学習コストも低いと思います。

**Comment by TeckService** [comment]
@SilversCat 確かに、今回のシステムは少しPHPでの開発は難しいところが幾つかあるように思えますね。
しかしながら、Pythonにした時に現状 開発が出来るメンバーは銀猫氏しかいらっしゃらないようでしたので、少し気がかりです。
その面についてはどうお考えですか？また、Pythonで開発するとどういったメリットがあるのでしょう。

**Comment by mnmonzk** [comment]
@SilversCat ありがとうございます。

**Comment by SilversCat** [comment]
@TeckService Pythonは、非常に可読性が高くメンテナンスやデバッグが容易です。
例えば、PHPで次のようなソースを書いたとします。

if ($a == $b) {  
    echo '$aと$bは等しい。';  
}  

御存知の通り、インデントや改行を取り除いても、文法的に正しければ動作するはずです。

if ($a == $b) {  echo '$aと$bは等しい。';  }

このようなソースが1つや2つならまだしも、何百個、何千個と現れれば、ソースコードを読み解くのは難しくなります。

Pythonだと、インデント及び改行を強制するため、読みにくいソースコードはそもそもエラーで止まってしまいます。

また、PHPは内部処理と表示するためのHTMLを分けることができません（多分あるのでしょうが、知りません）。  PythonのWebライブラリにはテンプレートエンジンが大抵の場合付属しています。

これらが利点でしょうか？

**Comment by PNGRU** [comment]
個人的な意見ですが、Laravelなどのフレームワークを利用することで、PHPでも多少なりとも可読性は向上するのではないのでしょうか。

**Comment by SilversCat** [comment]
@PNGRU Laravelについて調べてきました。
~~正直、PythonのFlaskのほうがより直感的だと思いました。~~

これでも良いと思います。ただ、Minecraftサーバーとの連携で引っかかりそうですね。
その点ではPythonのほうが適しているのでは？
（私が昔担当したプロジェクトもそこで引っかかって無事死亡しました。）

**Comment by mnmonzk** [comment]
自分も個人的な意見を述べさせていただきますが、PHPはAPIの開発として利用すべきだと考えます。

フロントエンド・バックエンドの処理を同じプログラムに収めてしまうと、メンテナンス性が損なわれ、非常に困難な開発の道をたどることになります(経験談)。

今回の場合、バック部分の開発はPHPを用い、フロント部分はPythonなどの言語を用いる事によって解消すると思うのですがいかがでしょうか

**Comment by SilversCat** [comment]
~~普通内部処理をPythonでやらない？(小声)~~

それでも良いかと思います。ただデットロックと整合性が損なわれるのがちょっと怖いかな。

**Comment by PNGRU** [comment]
なるほど。Pythonについて少し調べましたが、規約がある程度決まっているようなので可読性が高そうです。
しかし、言語を統一しなかった場合、SilverCat氏の言うように整合性などが失われる可能性もあると思います。

**Comment by mnmonzk** [comment]
確かに内部処理はPythonのほうが優れてますね。
今回の開発チームでは、Pythonを扱える方が現状 @SilversCat 氏以外いませんが、一任してもよろしいでしょうか。

**Comment by SilversCat** [comment]
@mnmonzk ﾜｫｵ･･･~~またかよ~~
構いません。ですが、私よりPythonが書ける人間がいるでしょうから探してほしいです。

**Comment by mnmonzk** [comment]
(もちろん追加要員は今後も募集しますのでご安心ください。)
では、Pythonをバックエンドで利用するということで問題ないでしょうか。

**Comment by SilversCat** [comment]
ええ、問題ありません

**Comment by mnmonzk** [comment]
最後決まっていない部分といえば、フロントエンド部分ですがこちらはどのような言語で実装しますか。(前に埋もれてたらそのまま投げてください)

**Comment by SilversCat** [comment]
このままで行くとPHPでしょうか？

**Comment by mnmonzk** [comment]
そのような感じですね。
ただ、現在オンライン人数が少ないように見えますのでこれについてはまた明日持ち越しとシたいと思います。

**Comment by mnmonzk** [comment]
おはようございます。
一応、 @mc-oops/developer ３分の２の人数の意見を聞いておきたいのでメンションしておきます。
バックエンドについて、PHPが有力ですがいかがでしょうか。

**Comment by SilversCat** [comment]
やぱり、Minecraftとの連携処理でPHPだとうまくいかない気がするのでバックエンドにはPythonを使用するべきだと思います。

**Comment by kory33** [comment]
Plugin部分にKotlinを使用することは賛成です。型安全性に加えNull安全性が保たれ、より開発のしやすい言語であると思います。ただし、Javaにある程度詳しい方のほうが言語になれるのが早く、いきなりKotlinで開発を始めるのは(公式ドキュメントがJava習得者向けに書かれている部分があるというのもあり)敷居が若干高いです。

ほとんどのインデントを強制しない言語でもLinterを導入することでファイル保存時のフォーマットチェック等を走らせることができます。コーディングスタイルの統一のためにも、インデントを強制する言語でもしない言語でもLinterの設定は入れておくべきだと意見します。

Web開発はNodeJS/PHPしか経験がないので何とも言えないのですが、 @SilversCat 氏のMinecraftとの連携処理についてもう少し詳しくお願いできますか？

**Comment by SilversCat** [comment]
@kory33 よくよく考えたらサーバーにUUIDとか投げるだけだからMinecraftの連動いらないっすね（今更）

**Comment by tearaikazuki** [comment]
@SilversCat なりすまし起きたらどうするのですか！

**Comment by SilversCat** [comment]
@tearaikazuki うーん。トークンを発行して照らし合わせるとか？

**Comment by kory33** [comment]
ソケットまたはデータベースを介した通信の場合はほとんどどの言語を使っても似たような感じにはなると思います。

@tearaikazuki なりすましが起こる可能性のある場所はどこを指しているのでしょうか？

**Comment by tearaikazuki** [comment]
@kory33 あ、なんか勘違いしてた()

**Comment by mnmonzk** [comment]
話が噛み合ってないように感じるので、一度「Minecraftサーバとの連携」について考えます。
バックエンド(API)は、Pythonで開発。
それを叩くためにMinecraftサーバ側プラグインをKotlin or Javaで開発する。
プラグインは、UUIDなどをAPIに投げればいいだけなので問題はないと考えるのですが…。

**Comment by SilversCat** [comment]
この処理としての問題は、プラグインでなくてもAPIを叩ければGBANできてしまうことです。
MCBANSのように認証システムを実装するべきです。

**Comment by mnmonzk** [comment]
そうですね。
しかし、ここの時点で止まっていると、このIssueがいつまで立っても解決しないので、別Issueに分離して解決します。

現在確定していることは、
- フロントエンド
    - PHP
- バックエンド
    - Python
- プラグイン
    - Kotlin
でよろしいでしょうか？

**Comment by junT58** [comment]
私は大丈夫だと思います。

**Comment by PNGRU** [comment]
大丈夫だと思います

**Comment by kory33** [comment]
大丈夫だと思いますっ

**Comment by SilversCat** [comment]
大丈夫でーす

**Comment by mnmonzk** [comment]
では、この通り進めます。
