### ISSUE TITLE
メールアドレスの取得

### ISSUE THREAD

**Issue by mnmonzk** [mc-oops/Conference#4]

**Comment by mnmonzk** [comment]
命名規則に従い、mc_oops@gmail.comを取得しようと考えているのですがいかがでしょうか。

**Comment by PNGRU** [comment]
良いと思います。
しかし、独自ドメインがあるのなら、`info@mc-oops.work` などでも良いと思います。

**Comment by tearaikazuki** [comment]
参考までに
![image](https://user-images.githubusercontent.com/19515213/31122818-50abd114-a878-11e7-8f1e-1476cada2e8b.png)

**Comment by PNGRU** [comment]
Outlook.com (マイクロソフト) の場合:
![](https://storage.ppn.pw/cc/img/5eb7a777/q7cc564d5.png)

**Comment by 32ba** [comment]
独自ドメインがあるなら、そちらを利用した方が良いと思います。

**Comment by mnmonzk** [comment]
@32ba ではその方向で調整しましょうか。

**Comment by PNGRU** [comment]
CoreServerですと、メールアカウントが作成できると思います。
参考: https://www.coreserver.jp/price/ **メール関連**

**Comment by mnmonzk** [comment]
@PNGRU 参考にさせていただきます。
ではこちらについては、既にProjectに上がっているとおり「使用するVPS?クラウド?の決定」で、インフラの @TeckService を絡め決めましょう。

**Comment by TeckService** [comment]
GmailやOutlookはよしたほうがいいでしょう。独自ドメイン方向で。
別に取得すること自体はなんら問題なくできますが、どうします？

もしメールアドレスを作成するのであれば、ツイッターやニコ動のアカウントも
独自ドメインのメールアドレスを使ってください。運用が楽なので。

**Comment by PNGRU** [comment]
独自ドメインを採用するほうが良いと思われます。
## 提案: メールアドレス案
**サポート用**: `support@mc-oops.work` `info@mc-oops.work`
**Webサイトからのメール送信用**: `no-reply@mc-oops.work`
(サービスごとにメールアドレスを分ける場合) `(サービス名) @mc-oops.work`
(分けない場合) `social@mc-oops.work`

などでどうでしょうか? @TeckService @mnmonzk

**Comment by mnmonzk** [comment]
よいと思います。

**Comment by SilversCat** [comment]
@PNGRU 氏の案を採用
