### ISSUE TITLE
使用するVPS?クラウド?の決定

### ISSUE THREAD

**Issue by SilversCat** [mc-oops/Conference#5]

**Comment by SilversCat** [comment]
やっぱり、王道を征くさくらのVPSですか。

**Comment by mnmonzk** [comment]
先程、 PNGRU氏が提案したCoreServerも案に入れています。
現在の候補は、
- さくらのVPS
- CoreServer

ですね。
このクラウドなどについては、 @TeckService 氏が来るまで保留としたいです。

**Comment by TeckService** [comment]
@SilversCat @mnmonzk 正直、プロジェクトが成功して安定した稼働が求められるようになるまでは、
投資するリスクも大きいので、最初は最低限の構成でもいいのではないでしょうか。

CORESERVER等でも、
過負荷時には機能制限をかけるようなシステムがあれば十分運用できると思います。

**Comment by SilversCat** [comment]
ん、そうですね。

**Comment by TeckService** [comment]
もちろんある程度安定稼働が求められるようになってくるようであれば、
ConoHa、さくら、GMOなどのクラウド、VPSサービスの利用も検討します。

**Comment by mnmonzk** [comment]
では、プロジェクト公開時、初期のサーバなどは何を利用しましょうか。

**Comment by SilversCat** [comment]
そうですねぇ・・・JMBANS時代は何を使用していたんです？

**Comment by tearaikazuki** [comment]
SikeServerって聞いた事がある()

**Comment by SilversCat** [comment]
あれは開発環境＝本番環境でしたから、おそらく参考になるかと。

**Comment by acid-chicken** [comment]
将来的にはAWS一択となってくると考えられますが、なかなか小規模で手がつけられるものでもありませんね。

**Comment by TeckService** [comment]
AWSやAzureだと現段階では導入コストが高いのでちょっとキツいです。
ましてや広告を設置しないとなると、どこからお金が...？っていう状況です。

最初はコアサーバー、さくら、GMOあたりの月額1000円以内のサーバーで運用したいのですが、どうでしょう？

**Comment by SilversCat** [comment]
やはりそれならさくらのVPN一択ですね。安心感が桁違いです

**Comment by mnmonzk** [comment]
では、さくらのVPSで勧めていく方向でよろしいでしょうか

**Comment by PNGRU** [comment]
良いと思います

**Comment by mnmonzk** [comment]
では、その方向で進めましょう。
