### ISSUE TITLE
開発割り振り

### ISSUE THREAD

**Issue by mnmonzk** [mc-oops/Conference#6]

**Comment by mnmonzk** [comment]
こちらについては、 @mc-oops/developer グループに追加されている人を対象とし、希望する開発チームをコメントしていただきます。

[Develop 開発言語](https://github.com/mc-oops/Conference/wiki/Develop-%E9%96%8B%E7%99%BA%E8%A8%80%E8%AA%9E)を参考にして、希望する担当箇所をコメントしてください。

**Comment by SilversCat** [comment]
バックエンド開発とプラグイン開発ができます。Kotlinはあまり使ったことがないので、バックエンド開発を希望します

**Comment by junT58** [comment]
フロントエンドとプラグインの開発が出来ると思いますが、Kotlinは使ったことがないので、フロントエンド中心でお願いしたいです。

**Comment by acid-chicken** [comment]
* Python
* PHP
* Kotlin

すべて軽く触った程度の技量ですのでどこでも構いません。

**Comment by PNGRU** [comment]
php, html等以外の言語は厳しいのでフロントエンドでよろしくお願いします。

**Comment by mnmonzk** [comment]
@suzukeno 回答お願いします。

**Comment by kory33** [comment]
1. Kotlinでのプラグイン開発
2. Pythonでの実装
3. PHPでの開発
の順で作業ができるかと思います。PythonとPHPの経験は少ないですのでプラグイン開発を第一希望とします

**Comment by mnmonzk** [comment]
全ての報告が確認されたのでクローズします。

**Comment by suzukeno** [comment]
遅刻勢だけどどれも似たような実力なんでバックエンド希望
