### ISSUE TITLE
全体の大まかな構造

### ISSUE THREAD

**Issue by mnmonzk** [mc-oops/Conference#7]

**Comment by SilversCat** [comment]
PLがBANコマンドを実行すると、ソケットを使った通信でBEにUUIDなどが送信され、BAN処理が実行されると同時にFEのBAN管理ダッシュボードがチャットに表示されるって感じですかね？

**Comment by mnmonzk** [comment]
![1](https://user-images.githubusercontent.com/31317056/31305422-493f887c-ab74-11e7-98bf-50c65ec2d1bc.png)

**Comment by mnmonzk** [comment]
通信方法は後々決めますが、ここでは本当に大雑把な構造をまとめます。
現状頭のなかで考えていることはこんな感じです

**Comment by mnmonzk** [comment]
では、以下のように分担を行い、開発を進めたいと思いますがいかがでしょうか？

## 図

![1](https://user-images.githubusercontent.com/31317056/31305568-d51e7f62-ab77-11e7-8512-7d5440bffeca.png)

## BE

- 認証
- FE、PLとの通信
- データベースとの通信

## FE

- デザインの作成
- WEBサイトの構築
- APIを利用してのデータの取得・表示

## PL

- APIを利用してのデータの取得・表示
- 処罰情報を追加・削除

## インフラチーム

- データベースの保守

**Comment by SilversCat** [comment]
良いと思います

**Comment by acid-chicken** [comment]
@tearaikazuki お構いなしにreactionをつけていてはreactionの意味がないのでは

**Comment by tearaikazuki** [comment]
@acid-chicken 失礼しました

**Comment by SilversCat** [comment]
:tada:につければいいので多分おそらく大丈夫

**Comment by mnmonzk** [comment]
@mc-oops/team では、以上のチームが開発の中心になって開発を進めます。
各チームのチーフは、mc-oopsにリポジトリを作成し、開発を開始してください。
開発中不明な点があれば、各リポジトリかConferenceにIssueを立てて質問してください。
