### ISSUE TITLE
データベース構造

### ISSUE THREAD

**Issue by mnmonzk** [mc-oops/Conference#8]
データベース構造の検討はこちらで行なってください。
BEチームは、このデータベース構造を元に実装を行ってください。

**Comment by mnmonzk** [comment]
まず、必要最低限のデータベースから考えていきます

**Comment by mnmonzk** [comment]
- 処罰情報テーブル

これ以外に考えられるテーブルがないのですがいかがでしょうか

**Comment by SilversCat** [comment]
えーっと認証のためのサーバー用テーブルとアカウント用テーブルが必要です

**Comment by mnmonzk** [comment]
- 処罰情報テーブル
- サーバテーブル

@SilversCat  アカウントテーブルについてですが、具体的にどのようなものですか？

**Comment by SilversCat** [comment]
認証に使用します。MCBANSのように処罰と処罰者を結びつけます。

**Comment by mnmonzk** [comment]
処罰と処罰者を結びつけた場合、何か利点はあるのでしょうか。

**Comment by SilversCat** [comment]
証拠の未提出などを追跡できます。また、悪意のあるBANなどから処罰者の信用度を算出することができます。

**Comment by mnmonzk** [comment]
なるほど、ありがとうございます。

- 処罰情報
- サーバ
- アカウント

以上の３つが最低限必要となるテーブルですが、他に追加などはありますか

**Comment by mnmonzk** [comment]
<img width="288" alt="2017-10-09 17 29 35" src="https://user-images.githubusercontent.com/31317056/31329978-71e35d9a-ad17-11e7-9d48-ce42b7fefd9a.png">
